import { 
  Server, Cpu, Wifi, Activity, 
  Thermometer, Settings, Power, Zap, 
  Radio, HardDrive, Database,
  Battery, BatteryCharging, Bluetooth,
  Camera, Cctv, Droplet, Fan, Gauge,
  Lightbulb, Lock, Shield, Wind,
  Sun, Snowflake, Flame, Plug, Router,
  Scale, Factory, Truck, Clock,
  Waves, GaugeCircle, CloudRain,
  Speaker, Siren, PlugZap,
  Satellite, Antenna, Signal,
  Microchip, Container, Cable,
  UtilityPole, Warehouse, Tractor,
  ZapOff, Airplay, Scan
} from 'lucide-react';

export const IOT_ICONS: Record<string, any> = {
  'server': Server,
  'cpu': Cpu,
  'wifi': Wifi,
  'activity': Activity,
  'thermometer': Thermometer,
  'settings': Settings,
  'power': Power,
  'zap': Zap,
  'radio': Radio,
  'hard-drive': HardDrive,
  'database': Database,
  'battery': Battery,
  'battery-charging': BatteryCharging,
  'bluetooth': Bluetooth,
  'camera': Camera,
  'cctv': Cctv,
  'droplet': Droplet,
  'waves': Waves,
  'fan': Fan,
  'gauge': Gauge,
  'gauge-circle': GaugeCircle,
  'lightbulb': Lightbulb,
  'lock': Lock,
  'shield': Shield,
  'wind': Wind,
  'sun': Sun,
  'snowflake': Snowflake,
  'flame': Flame,
  'plug': Plug,
  'plug-zap': PlugZap,
  'router': Router,
  'signal': Signal,
  'antenna': Antenna,
  'satellite': Satellite,
  'scale': Scale,
  'factory': Factory,
  'warehouse': Warehouse,
  'container': Container,
  'cable': Cable,
  'microchip': Microchip,
  'truck': Truck,
  'tractor': Tractor,
  'utility-pole': UtilityPole,
  'clock': Clock,
  'rain': CloudRain,
  'speaker': Speaker,
  'siren': Siren,
  'zap-off': ZapOff,
  'airplay': Airplay,
  'scan': Scan
};

export function getDeviceIcon(iconId?: string) {
  if (!iconId) return Server;
  return IOT_ICONS[iconId] || Server;
}
