import type { Device } from '../types';

export const mockDevices: Device[] = [
  {
    id: 'DEV-001',
    name: 'Main Energy Meter',
    type: 'energy_meter',
    tags: ['factory-a'],
    metrics: {
      voltage: 220,
      current: 18.5,
      power: 4070,
      energy_today: 128.6,
    },
    status: 'online',
    lastSeen: new Date().toISOString(),
    firmwareVersion: 'v1.2.0',
  },
  {
    id: 'DEV-002',
    name: 'CNC Machine 1 Power',
    type: 'energy_meter',
    tags: ['factory-a'],
    metrics: {
      voltage: 380,
      current: 45.2,
      power: 17176,
      energy_today: 450.2,
    },
    status: 'warning',
    lastSeen: new Date(Date.now() - 5 * 60000).toISOString(),
    firmwareVersion: 'v1.1.8',
  },
  {
    id: 'DEV-003',
    name: 'Air Compressor 1',
    type: 'air_compressor',
    tags: ['factory-a', 'air-compressor'],
    metrics: {
      pressure: 7.8,
      temperature: 85,
      power: 22000,
      running_hours: 1450,
      leakage_rate: 3.2,
    },
    status: 'online',
    lastSeen: new Date().toISOString(),
    firmwareVersion: 'v2.0.1',
  },
  {
    id: 'DEV-004',
    name: 'Cold Storage Ambient',
    type: 'temperature_sensor',
    tags: ['factory-a', 'cold-storage'],
    metrics: {
      temperature: -18.5,
      humidity: 45,
      door_open_events: 7,
      battery: 85,
    },
    status: 'online',
    lastSeen: new Date().toISOString(),
    firmwareVersion: 'v1.0.5',
  },
  {
    id: 'GW-001',
    name: 'Factory Main Gateway',
    type: 'gateway',
    tags: ['factory-a'],
    metrics: {
      cpu: 45,
      ram: 60,
      uptime: 720,
    },
    status: 'online',
    lastSeen: new Date().toISOString(),
    firmwareVersion: 'v3.5.0',
  },
  {
    id: 'SOL-001',
    name: 'Rooftop PV Inverter',
    type: 'solar_inverter',
    tags: ['solar'],
    metrics: {
      power: 18400,
      energy_today: 1840,
      efficiency: 96.8,
      battery_soc: 78,
    },
    status: 'online',
    lastSeen: new Date().toISOString(),
    firmwareVersion: 'v1.8.2',
  },
  {
    id: 'PMP-001',
    name: 'Water Pump Controller',
    type: 'pump_controller',
    tags: ['water-pump'],
    metrics: {
      flow_rate: 128,
      pressure: 4.6,
      running_hours: 18.2,
      power: 9600,
    },
    status: 'online',
    lastSeen: new Date().toISOString(),
    firmwareVersion: 'v2.3.1',
  },
];
